http {

    include mime.types;

    server {
        listen 8080;
        root /Users/laithharb/Desktop/mysite;

        location /fruits {
            root /Users/laithharb/Desktop/mysite;
        }

        location /carbs {
            root /Users/laithharb/Desktop/mysite;
        }
    }

    events {}
}