http {

    include mime.types;
	root content;

     server {
        # listen 8080;
		listen localhost:8080;
		listen localhost:5143;
		# listen ;
        root content;
		client_max_body_size 1000;
		server_name www.hello.com hello.com www.hello hello;

		allowed_methods GET DELETE;

		location / {}

		location /content {
			root .
		}

		location /files {
            root content;
			autoindex on;
			allowed_methods GET DELETE;
        }

        location /uploads {
            root content;
			allowed_methods POST;
        }

		location /cgi-bin {
            root content;
			allowed_methods GET POST;
			cgi_extension .py /usr/bin/python3;
        }

		location /fruits {
			return 301 /content/files/index.html;
		}

		location /fruits/noslash {
			return 301 noslash;
		}

		location /fruits/fruits {
			return 301 /content/files/index.html;
		}
    }
}