http {

    include mime.types;

    server {
        listen localhost:8080;
		listen 5143;
		root content;
		client_max_body_size 1000;
		server_name www.hello.com hello.com www.hello hello;

        location /404.html {
			root content/errors;
		}

		location /fruits {
			return 301 /content/files/index.html;
		}
		

        location /files {
            root content;
			allowed_methods GET POST DELETE;
        }

        location /uploads {
            root content;
			allowed_methods POST;
        }
    }

	server {
        listen 80;
		listen 8080;
		listen *:6222;
		listen 127.0.0.1:*;
		root content;
		server_name mayonesa.com;
		
		location /404.html {
			root content/errors;
		}

		location /fruits {
			return 301 /content/files/index.html;
		}
    }

	server {
		listen 80;
		listen 8080;
		listen 6222;
		listen 6222;
		root content;
		client_max_body_size 2000;
		server_name www.crotalo.com crotalo.com;

        location /uploads {
            root content;
			allowed_methods POST;
        }
	}
}